:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:20]
:ID:       ce64c9a4-44e3-4b3a-860b-a74c6baff528
:END:
#+title: Notes on using Emacs
#+filetags:  emacs

* Emacs Refcards
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       7a562f06-4f89-42a1-a83d-a3d1fba23e3d
:END:
  - M-x locate <RET> refcard <RET>
  - profit.
* Clj -> Elisp Cheat Sheet
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       72cb0317-95bb-4d26-b4ae-03b3588b5dff
:END:
** map = mapcar
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       f155caaf-c551-49aa-8dfa-d98dfd68027d
:END:
mapc is similar to mapcar, expect that it does not accumulate the results.
mapc should be used for side-effects, where we don't care about the
return value.
** apply = apply
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       605eaf64-5468-46f1-ad66-f8674686ebd7
:END:
The way to call this is:
(apply #'equal '(:a :A))
** keep = delq nil
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       1a6907f0-c9ef-458d-b024-112033f759d6
:END:
** = = equal
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       c4682d46-b1f6-42fd-9ec9-aefbd857e99c
:END:
** first = car
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       2e77e7e0-fcd1-43f4-95d9-888c64a51d1a
:END:
** rest = cdr
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       aa8db6b5-4184-4732-88d6-063ab628f1e8
:END:
** Other Notes:
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       4070eae1-ecd2-4808-8a77-5584f3b1f6e6
:END:
The function `funcall` can be used to treat the first argument as a
function on the rest of the arguments.

Eg: (funcall #'equal :a :A) => nil
    (funcall #'equal :a :a) => t

* Regex replacements
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       6202bc0e-6d49-4302-a4a9-05f24f493205
:END:
  Taken right from the Emacs Manual (I always seem to forget this).
  http://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Replace.html

  M-x replace-regexp <RET> c[ad]+r <RET> \&-safe <RET>
  replaces (for example) ‘cadr’ with ‘cadr-safe’ and ‘cddr’ with ‘cddr-safe’.

  M-x replace-regexp <RET> \(c[ad]+r\)-safe <RET> \1 <RET>
  ‘\d’ in newstring, where d is a digit, stands for whatever matched the dth
  parenthesized grouping in regexp.
  Note : The parens making groups need to be escaped.

* How to check dependents of a library
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       55125e2d-597b-4604-b058-b29c04f0b21e
:END:
#+begin_src emacs-lisp
  (require 'loadhist)
  (file-dependents (feature-file 'cl))
#+end_src

* Compiling and Running Emacs 28 on master branch (Ubuntu)
:PROPERTIES:
:ID:       700381b6-78ef-4abb-9f68-6b514b5b83ba
:END:
** Set up the prerequisite libraries
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       8c88714b-8cda-4b0f-8e60-8c30132d0d99
:END:
This command is created by:
1. Run the command ~sudo apt build-dep emacs~ and copy all the packages it will install. (*Don't actually install the packages*)
2. Remove all the ImageMagick related libraries from this command, we have installed it from source.
3. Review the output of ~./configure~ command in Emacs. See if there are new options which are not covered by your distribution's old version of Emacs.

#+begin_src sh :eval no
  sudo apt install libx11-dev libtiff5-dev libtiff-dev libgif-dev libjpeg-dev libpng-dev libxpm-dev libcairo2-dev libexif-dev libexpat1-dev libglx-dev libgmp-dev libgnutls-openssl27 libgnutls28-dev libgraphite2-dev libharfbuzz-dev libharfbuzz-gobject0 libice-dev libidn2-dev libilmbase-dev libilmbase25 libjbig-dev libjpeg-turbo8-dev libgnutlsxx28 libjpeg8-dev liblcms2-dev liblockfile-bin liblockfile-dev liblockfile1 liblqr-1-0 liblqr-1-0-dev libltdl-dev liblzma-dev libm17n-0 libm17n-dev libgtk-3-dev libncurses-dev libncurses5-dev libopenexr-dev libopenexr25 libopengl-dev libopengl0 libotf-dev libotf0 libp11-kit-dev libpango1.0-dev libpixman-1-dev libpng-dev libpthread-stubs0-dev librsvg2-dev libsm-dev libsub-override-perl libsystemd-dev libtasn1-6-dev libthai-dev libtiff-dev libtiffxx5 libtool libunbound8 libwayland-bin libwayland-dev libwmf-dev libwmf0.2-7 libx11-dev libxau-dev libxaw7-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbcommon-dev libxmu-dev libxmu-headers libxpm-dev libxrandr-dev libxrender-dev libxt-dev libxtst-dev m17n-db nettle-dev pango1.0-tools po-debconf postfix quilt sharutils wayland-protocols x11proto-core-dev x11proto-dev x11proto-input-dev x11proto-randr-dev x11proto-record-dev x11proto-xext-dev x11proto-xinerama-dev xaw3dg xaw3dg-dev xorg-sgml-doctools xtrans-dev xutils-dev gnutls-bin graphviz autopoint gsfonts libxaw3dxft8-dev libwebkit2gtk-4.0-dev libgccjit-10-dev libjson-c-dev libjson-glib-dev libjansson-dev
#+end_src
** Run the installation commands from inside Emacs source directory
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       e7f2e40a-8df2-48ce-9311-fcd086e5f81a
:END:
#+begin_src shell-script
  make distclean
  ./autogen.sh
  ./configure --with-imagemagick --with-json --with-native-compilation --with-xft --with-xwidgets --with-pgtk
  # Alternative configure command:
  ./configure --without-toolkit-scroll-bars --with-x-toolkit=gtk3 --with-xpm=ifavailable --with-jpeg=ifavailable --with-gif=ifavailable --with-tiff=ifavailable --with-xml2 --with-rsvg --without-pop --with-png --with-mailutils --with-native-compilation --with-cairo --with-harfbuzz
  # If everything works
  make bootstrap
  # If everything works
  make
  # Test the binary
  src/emacs -Q
  # Install the binary
  sudo make install
#+end_src
* Compiling and Running Emacs 29 on master branch (Mac)
:PROPERTIES:
:ID:       375BA0A4-6D52-4CDC-873B-1D0BBCE35682
:END:
I successfully compiled Emacs from source on the M1 Macbook Air right now (from https://github.com/jimeh/build-emacs-for-macos/). Noting down the steps in the hopes it will help others.

Initially, I had a linker failure ~ld: library not found for -lwebp~. I added the line ~brew 'webp'~ to the ~Brewfile~ to install this dependency. However, later I realized that the problem was because the correct ~LIBRARY_PATH~ was not being set. So I'm not sure if this change is needed.

The actual commands I executed were:
#+begin_src sh :eval no
  brew bundle
  export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/lib/
  export CPATH=$CPATH:/opt/homebrew/include/
  ./build-emacs-for-macos --git-sha c00ffe263d9ffeb4d2a5e13cc124c786152137db
#+end_src

Once compilation was successful, I extracted the ~.tbz~ file created under ~builds~ and signed it as explained in https://github.com/jimeh/build-emacs-for-macos/pull/65/files
#+begin_src sh :eval no
  codesign --force --deep -s - Emacs.app
#+end_src

* Org Mode common stuff that I always look for
:PROPERTIES:
:CREATED:  [2022-07-13 Wed 13:59]
:ID:       FF0D6989-D3BB-492F-865C-CBBE5E8B7DC3
:END:
- I'm always looking for stuff in [[brain:954F3561-36FC-4329-99DC-E1F4D7135CC1][Org-Mode Tables]], so check there for common tasks first.

* Dired Tips                                                          :dired:
:PROPERTIES:
:CREATED:  [2022-10-02 Sun 08:35]
:ID:       F019FED4-F76A-4588-8A54-FC494FB3008B
:END:
** Dired tips from ilemming
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       df417075-8e47-4abe-905b-acd8866c494f
:END:
- All tips taken from https://twitter.com/search?lang=en&q=dired%20(from%3Ailemming)
*** Show commits related to specific files                            :magit:
:PROPERTIES:
:URL:      https://twitter.com/iLemming/status/1193025618742349824
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       b956ee3f-b02f-4010-9fef-34179a69e750
:END:
Did you know, you can mark files in Dired buffer and then do

=M-x magit-dired-log=

and it will show commits but only related to those files?
*** Find files containing specific phrase
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       2fd8d651-ade1-4462-be7f-cc6666d7f7bf
:END:
Let's say you want to recursively find all =*.scss= files and then
mark those that contain "mixin", so you can then move them or rename,
delete etc.
#+begin_example
M-x find-name-dired
% g mixin
#+end_example
*** Recursively display directory data. Peeking
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       cc4ab34a-7088-4677-8cf8-e89e7cdb298c
:END:
Of course you know about this feature of dired-mode.

You can "peek" into a subdirectory by pressing <i>

But did you know you can "insert" dirs recursively?

Use an argument and -R option.

=C-u i  -R RET=
*** Dynamically filter directory listing
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       4750d3d0-b75b-4785-84b5-8c52d313fbbf
:END:
- Install =dired-narrow=
*** Dired: Send content to external programs
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       fa4c35f8-b75a-421b-acde-c7666766a1cc
:END:
Let's continue on sending content to external apps.

You can mark files in Dired-mode and pipe them into a program.

- Mark files - =m=
- M-x dired-do-shell-command - =!= or =X=
- M-x dired-do-shell-command-async - =&=
- Command: =wc-l= to run the command on each marked file, =wc -l *= to
  run the command on all the files in one go.
*** Dired: turn arbitrary shell output to a dired buffer
:PROPERTIES:
:CREATED:  [2021-04-22 Thu 22:07]
:ID:       5840c7da-76ec-43fb-8cbb-d8369c7485bc
:END:
Did you know that textual representation of a directory can be turned into a legit Dired buffer in @emacs
?

- get output of "find" or "ls",
- edit it,
- then do `M-x dired-virtual`

if you're still not convinced that Emacs is dope - stay tuned, I'll keep posting cool tips

** Rename multiple files in Dired
:PROPERTIES:
:CREATED:  [2022-10-02 Sun 08:35]
:ID:       FD5D2663-0E97-4243-AC29-D775F0C3B01E
:END:
- Use =wdired= for this.
- Activate writable mode in Dired using =M-x dired-toggle-read-only= or =C-x C-q=
- Make all the edits as you would in a normal buffer
- Exit Wdired and commit the changes, using =C-x C-s= or =C-c C-c=
* Emacs and SQL
:PROPERTIES:
:CREATED:  [2023-01-27 Fri 11:12]
:ID:       B1EAB62D-6A3D-4C2C-BC5B-CF14354BC9A1
:END:
~sql-interactive-mode~ is excellent and my preferred way of interactive with a database that supports SQL.

To start a SQLi buffer + work against a database:

1. ~M-x sql-<name-of-db>~ (eg: ~sql-postgres~). If you have the ~.dir-locals.el~ file (see below), values will be auto filled in. This will start an interactive SQL buffer.
2. Open a .sql file to write SQL in.
3. In this file, ~M-x sql-set-product~, followed by ~M-x sql-set-sqli-buffer~.

To speed up connection to an SQL database, add the following to a ~.dir-locals.el~ file:

#+begin_src emacs-lisp
  ((sql-mode . ((sql-product . postgres)
                (sql-user . "pgw")
                (sql-password . "")
                (sql-port . 5432)
                (sql-server . "192.168.33.10")
                (sql-database . "pgw-main"))))
#+end_src

* RESTRUCTURED Installing Emacs from source                        :noexport:
CLOSED: [2021-10-18 Mon 18:01]
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       11884933-cb35-491d-b6d3-889b6844253f
:END:
:LOGBOOK:
- State "RESTRUCTURED" from              [2021-10-18 Mon 18:01] \\
  Outdated now, please refer to [[id:700381b6-78ef-4abb-9f68-6b514b5b83ba][Compiling and Running Emacs 28 on master branch (Ubuntu).]]
:END:

** Ubuntu 12.04
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       a0a34a92-c1ee-4a37-86bb-7f985191bd22
:END:

$ git clone git://git.savannah.gnu.org/emacs.git

$ sudo apt-get install libxaw7-dev libjpeg-dev libgif-dev libxpm-dev
libpng12-dev libtiff4-dev libncurses5-dev libtinfo-dev libglib2.0-dev
intl-fonts libgtk2.0-dev libxaw3dxft6 librsvg2-dev imagemagick libdbus-1-dev
libgconf2-dev libm17n-dev libotf-dev graphicsmagick-libmagick-dev-compat

# This second step can probably be avoided/replaced with
# $ sudo build-dep emacs
# Need to try that out one of these days

$ make distclean
$ ./autogen.sh
$ ./configure --prefix=/opt/emacs/ --with-xft --with-x-toolkit
$ make bootstrap
$ sudo make install

** Mac OS X 10.7
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       55ce3338-410b-4560-ad5f-87398db10e2d
:END:

$ brew install emacs --HEAD --cocoa --use-git-head

$ brew linkapps

# After installing from brew, head to /Library/Caches/Homebrew/emacs--git/
# (source is downloaded here) and make tags for the source

$ make tags
* RESTRUCTURED Compiling and Running Emacs 28 on the native-comp feature branch (Ubuntu). :noexport:
CLOSED: [2021-10-18 Mon 18:02]
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       f3936699-9215-48d4-b14a-62b08043d6d8
:END:
:LOGBOOK:
- State "RESTRUCTURED" from              [2021-10-18 Mon 18:02] \\
  - Outdated, please refer to [[id:700381b6-78ef-4abb-9f68-6b514b5b83ba][Compiling and Running Emacs 28 on master branch (Ubuntu).]]
:END:
** The gist of it, building Emacs from Source
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       c6d5889c-57d9-42b4-ba78-653d7f8ed058
:END:
  #+begin_src shell-script
    ./autogen.sh
    ./configure --with-nativecomp
    # If everything works
    make
    # Test the binary
    src/emacs -Q
    # Install the binary
    sudo make install
  #+end_src
** Problems during Installation
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       d723db24-90ce-4526-8a8f-af1b566177ea
:END:
*** Configure fails because libgccjit fails the smoketest
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       db4ac342-1450-4bae-ba0e-251ed9cf0216
:END:
- Ensure that libgccjit is installed and at the latest version (at
  this point in time, the latest version is 10)
- Ensure that gcc is at the same version as libgccjit (also 10)
- Install the Ubuntu toolchain PPA for the latest versions of gcc and libgccjit.
  + https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa
- After updating / installing the latest gcc, libgccjit-* packages,
  you will need to use update-alternatives to ensure that the correct
  tools are being picked.
  #+begin_src shell-script :eval no
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
    sudo update-alternatives --config gcc
    sudo update-alternatives --config g++
  #+end_src
- Ensure that gcc-10 is selected, so that you don't see the 'failed
  smoke test' error message from libgccjit.
*** Configure fails because various libraries don't exist on your system.
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       264d9eac-39bd-4937-a3b6-4f845b965f11
:END:
- Emacs needs a number of different libraries during compilation. You
  should look for an install the =-dev= version of any such libraries
  that are missing. (Eg: =libxpm-dev=, =libgif-dev=, =libtiff-dev=)
** Problems Post Installation
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       74b99997-5c55-4825-9254-63adfbe43d15
:END:
*** You need to generate native compiled files for all your emacs-lisp code
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       fd203d28-8a32-45b5-86e5-9b9183656b85
:END:
- Add this to your init.el
  #+begin_src emacs-lisp
    (if (and (fboundp 'native-comp-available-p)
             (native-comp-available-p))
        (setq comp-deferred-compilation t)
      (message "Native complation is *not* available"))
  #+end_src
- The message in the above code will also tell you whether the Native
  Compilation binary is correctly built.
- As a one-time run, you can also execute the following code after  =M-x ielm=
    #+begin_src emacs-lisp
      (native-compile-async "/home/<yourname>/.emacs.d" t)
    #+end_src
- This will create all the necessary =.eln= files for you.
*** You need to clean install your packages, preferably the latest versions of the packages
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       58929e92-dffa-4163-bef7-a38ad5df183f
:END:
- Best to just reinstall all the packages you depend on, to ensure
  that they get compiled properly.
*** Start and profit, huge speed boosts.
:PROPERTIES:
:CREATED:  [2021-11-27 Sat 09:56]
:ID:       f9f1f647-182d-4359-a13b-efdaf1b99434
:END:
- Very little configuration code broke for me (only one =isearch=
  modification broke, which used =substitute-key-definition= and
  substituted a function which took optional arguments with another
  function which took 0 arguments. This seems to not work within
  native compilation.
