:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       1518f569-dbda-4abd-a1bb-39856423d5f5
:END:
#+title: Tips and Tricks on MacOS
* Change the Lock Screen Keyboard Shortcut on your Mac
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       74e093a7-5b6d-4c16-af36-b37933d760fe
:END:
- Why? Because the default lock screen keyboard shortcut interferes with important Emacs key-bindings
- Launch System Preferences and go to the Keyboard pane.
- Select the 'Keyboard Shortcuts' tab.
- From the list on the left, select 'Application Shortcuts'.
- Click on the plus (+) button below to add your new shortcut.
- In the dialog box we'll want to leave 'All Applications' selected in the first menu. Enter 'Lock Screen' as the Menu Title. Please note this has to be exactly the same name you entered when saving the service in Automator. Finally, enter your keyboard shortcut. Let's go with Option+Shift+Q
- Click Add and you're all done!

* Turn the wifi on/off from the terminal on your Mac
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       f06189ab-092c-42c0-a96c-b2a217633bd2
:END:
  - You have to use =networksetup= for this
    #+begin_src shell-script
      # List all the hardware ports controlled by networksetup
      networksetup -listallhardwareports
      # Turn the wifi on
      networksetup -setairportpower en0 on # or off
    #+end_src

* Check if your Mac machine is overheating
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       d0b7c3e0-b545-4150-a731-bebe0e549dc7
:END:
  #+begin_src sh :eval no
    pmset -g thermlog
  #+end_src

* Storing and Using secrets in shell scripts and config files on MacOSX
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:11]
:ID:       3fa0dfe5-53ba-47c7-a19d-ef3bdfbb9940
:BRAIN_PARENTS: FCE04B5D-71FB-4A3B-9ABC-FB9B6A531BE2
:END:
:RESOURCES:
- [[https://www.netmeister.org/blog/keychain-passwords.html][Using the OS X Keychain to store and retrieve passwords]]
:END:
If you have a local script or ~.bashrc~ or some other config script, avoid exporting/setting secret variables directly in these scripts. Instead:

1. Open *Keychain Access.app*
2. Add a new keychain from *File > New keychain*
   - Using new keychain will allow you to use a different password than login for storing secrets.
   - You can also use the login keychain, if you don't want to enter password each time
3. Add a name for the keychain, once you will click on Save button, it will ask to enter the password for the new keychain.
   - Add a decently complex password.
4. Once added, select the newly created keychain from the left pane of the Keychain Access app.
5. To add a new password item, select *File > New Password Item*. Fill in the following details:
   - Keychain item name: This is the keyword to access your keychain item.
   - Account Name: This could be anything, usually used to group 1 or more password items
   - Password: This is the secret you want to store in the Keychain against this item.
6. Once added, you should test the secret access in terminal with following command:
   #+begin_src sh :eval no
     security find-generic-password -a TEST_account_name -s TEST_item_name -w
   #+end_src

To load secrets, you can now create a function in your script as follows:
#+begin_src sh :eval no
  function load_secrets () {
    export SECRET1=$(security find-generic-password -a TEST_account1 -s TEST_item1 -w)
    export SECRET2=$(security find-generic-password -a TEST_account1 -s TEST_item2 -w)
  }
#+end_src

* Homebrew Tips and Tricks
Denote file at: [[denote:20240330T203426][Homebrew tips and tricks]]
** To see which installed packages use a certain package
=brew uses --installed xz=

* Programming languages on the Mac
These are experiments that have not graduated to my main setup yet.
** Install the Bend programming language
Details at: https://github.com/HigherOrderCO/bend

#+begin_src fish
  brew install hvm
  hvm --version
  brew install bend-lang
  bend --version
#+end_src
* My personal Operating System setup from scratch for macOS Monterey
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       eec0482f-6b83-45f7-b584-d42fd13d3bef
:END:
** Mac: Install my favorite Nerd Fonts
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       a623ed27-7628-44ae-8568-2088b1b3e79b
:END:
- Download Fantasque NF and MesloLGS NF from https://www.nerdfonts.com/font-downloads

** Mac: Install the basics for getting started with anything else
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       7c821c94-9d93-4bc5-a157-82047ff841f4
:END:
- Install ~brew~ from https://brew.sh
- Install common packages from ~brew~, as mentioned in the section copied from my Ubuntu guide (pasted below)
- After completing common package installation, install casks and packages specific to MacOS
  #+begin_src sh :eval no
    brew install ledger pinentry-mac gnu-sed gnupg gnuplot coreutils dog neofetch pandoc ffmpeg qpdf zig fossil protobuf sccache marksman tailscale
  #+end_src
  #+begin_src sh :eval no
    brew install --cask brave-browser discord docker ghostty iterm2 keepassxc maccy macfuse mactex signal transmission tresorit vlc whatsapp zulip
  #+end_src

*** Ubuntu: Install the basics for getting started with anything else
- Common packages (Replace ~sudo apt~ with ~brew~ for Mac OS)
  #+begin_src sh :eval no
    sudo apt install tmux mercurial subversion aspell automake texinfo shellcheck tree wget curl trurl git jq direnv
  #+end_src
- Linux specific packages
  #+begin_src sh :eval no
    sudo apt install gnome-tweaks aspell-en gawk default-jre-headless default-jre
  #+end_src

** Mac: Set up file sharing to access private files
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       d1581c2b-4d38-4820-b931-96ae0944c1dd
:END:
Follow the instructions below to set up my private dotfiles.

*** Ubuntu: Set up file sharing to access private files
- Setup my file-sharing systems to get access to my common files
- Symlink my ssh keys and gpg keys from my file-sharing systems to the home dir
- Make sure that [[denote:20220104T133800::#h:4419B7EB-765E-4BF8-A6E8-1A4175A83C73][Notes on GnuPG / GPG::How to copy your .gpg folder and set the correct permissions]]

** Mac: Clone my public dotfiles into my source folder
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       0e5ed504-8d54-4de7-a1eb-f31e4f4915c3
:END:
- Symlink ~.gitconfig~ and ~.gitattributes~ from my public ~dotfiles~ to the home dir.

** Mac: Install fish shell
#+begin_src fish
  brew install fish
#+end_src

After installing ~fish~, install ~fisher~. Then install the following plugins:
- ~fisher install jorgebucaran/fisher~
- ~fisher install jorgebucaran/nvm.fish~
- ~fisher install ilancosman/tide@v6~

** Mac: Install Rust and Rust based CLI tools
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       6781bcab-99e0-420c-a74f-0b13d161021b
:END:
The CLI tools mentioned here are great productivity boosters. Check them out by searching for them if you are not sure what they do.

Follow the instructions below to install Rust and Rust based CLI tools.

- Install Rust using Rustup as described at https://www.rust-lang.org/learn/get-started
- Install all the tools I use
  #+begin_src fish :eval no
    cargo install --locked atuin bat difftastic dprint du-dust exa fd-find git-delta hyperfine jless mergiraf procs ripgrep rust-analyzer sd sqlx-cli tagref tealdeer tokei vivid vl-convert websocat zoxide
  #+end_src

** Mac: Install Go and Go based CLI Tools
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       c0de3a60-6c61-45ab-a535-23dca168b894
:END:
- Install ~golang~ from ~brew~
  #+begin_src sh :eval no
  brew install golang
  #+end_src
- Install ~gopls~ (LSP) by following instructions in Go Wiki: https://pkg.go.dev/golang.org/x/tools/gopls#section-readme
- Install Go CLI tools from ~brew~
  #+begin_src sh :eval no
  brew install dbmate gron
  #+end_src

** Mac: Install Jujutsu as my main VCS driver
Note that we need to have completed the Rust step above before we do this.

#+begin_src fish
  # To install the *prerelease* version from the main branch
  cargo install --git https://github.com/jj-vcs/jj.git \
       --locked --bin jj jj-cli
#+end_src

** Mac: Install tmux-tpm from source
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       c67cb4bd-e63d-45cd-9e27-d786cb642118
:END:
Follow the instructions below to install ~tpm~ : The ~tmux~ plugin manager

- Symlink ~.tmux.conf~ to home dir
- Clone the ~tmux-tpm~ repo
  #+begin_src sh :eval no
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  #+end_src
- Execute ~C-b I~ inside tmux once to install all the plugins

** Mac: Install everything needed for Clojure development
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       c25c8d41-6e2e-4412-8826-df0d97ee6cb8
:END:
#+begin_src sh :eval no
  brew install clojure/tools/clojure borkdude/brew/clj-kondo borkdude/brew/babashka cljstyle borkdude/brew/jet lilactown/brew/eql clojure-lsp/brew/clojure-lsp-native
#+end_src

*** Install jdk sources
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       b2ddefdf-390a-4e5a-aa92-c82eaa5013c3
:END:
#+begin_src sh :eval no
  brew install --cask temurin@25
  brew install visualvm mvn
#+end_src

** Mac: Setup email via notmuch
- Install notmuch deps manually
  #+begin_src sh :eval no
  brew install xapian gmime talloc zlib notmuch msmtp isync
  #+end_src
- Symlink ~notmuch/.notmuch-config~, ~.mbsyncrc~ and ~.msmtprc~ from private dotfiles to Home.
- Symlink ~notmuch~ dir in private-dotfiles to ~<maildir>/.notmuch/hooks~

** Mac: Install Emacs from jimeh-builds
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       8e38eec9-c1df-4a8c-85f6-978cee261331
:END:
- Download and install the latest version from jimeh-builds
- Clone https://github.com/unravel-team/emacs to ~.emacs.d~
- Clone https://github.com/cask/cask to ~.cask~ in order to run cask based tests
- Symlink my  ~personal.el~ file and ~common.el~ file from private dotfiles into ~.emacs.d~

** Mac: Install uv for managing python tools and projects
#+begin_src sh :eval no
  brew install uv
#+end_src
- ~Pygments~ provides source code highlighting in ~org-exports~
#+begin_src sh :eval no
  uv tool install shell_sage llm aider-ce
#+end_src
*** LLM plugins
1. ~llm install llm-gemini~ (for Gemini support)
2. ~llm install llm-cerebras~ (for Cerebras support)

** Mac: Install pympress for PDF based presentations
#+begin_src sh :eval no
  # Doesn't need other packages because they have been previously installed
  brew install pympress
#+end_src

** Mac: Install yt-dlp for downloading videos from Youtube
#+begin_src sh :eval no
  brew install yt-dlp
#+end_src

** Mac: Install tooling for Javascript
- We have already installed =nvm= as part of =nvm.fish=. Now install node via nvm
#+begin_src sh :eval no
  nvm install 24
#+end_src
- We also set the ~nvm_default_version~ env var in our fish config, so that the default is v24
- Finally, install =bun= at the system level, to use instead of =node=.
  #+begin_src sh :eval no
  curl command to install bun.sh
  #+end_src
** Mac: Install elm and tools for elm
1. Install elm: =brew install elm=
2. Install elm tooling:
   1. =bun install -g @elm-tooling/elm-language-server=
   2. =bun install -g elm-format=

** Mac: Install AWS CLI for accessing ECR
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       ecae10ce-f843-4315-9b56-e32961acd5f7
:END:
- =brew install awscli=
- =awscli configure=
- =aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin <ecr-bucket>=

** Mac: Install tarsnap for setting up backup
:PROPERTIES:
:CREATED:  [2022-03-21 Mon 13:10]
:ID:       e31877fe-10da-4ca7-9b57-188515d8bfc3
:END:
- =brew install openssl=
- Follow instructions on the tarsnap site for compilation

** Mac: Install pgFormatter
- pgFormatter is a perl script and needs to be installed manually.
- Download the ~pg_format~ script from https://raw.githubusercontent.com/darold/pgFormatter/master/pg_format
  #+begin_src sh :eval no
    curl -O https://raw.githubusercontent.com/darold/pgFormatter/master/pg_format
  #+end_src
- Make sure it is executable and copy it to somewhere on your PATH
** Mac: Install toxiproxy
Project Page: https://github.com/Shopify/toxiproxy

#+begin_src sh :eval no
  brew tap shopify/shopify
  brew install toxiproxy
#+end_src

** Mac: Install awscli and rclone
These are important tools for cloud storage management. Both need setup management.

#+begin_src sh :eval no
  brew install awscli
#+end_src
For AWS CLI config, run ~aws configure sso~ to create a profile that you can use for all other AWS commands.

For rclone setup, refer to https://rclone.org/install/ and install the pre-compiled binary using curl
#+begin_src sh :eval no
  cd && \
      curl -O https://downloads.rclone.org/rclone-current-osx-amd64.zip && \
      unzip -a rclone-current-osx-amd64.zip && \
      cd rclone-*-osx-amd64
#+end_src

#+begin_src sh :eval no
  sudo mkdir -p /usr/local/bin && \
      sudo mv rclone /usr/local/bin/
#+end_src
#+begin_src sh :eval no
  cd .. && rm -rf rclone-*-osx-amd64 rclone-current-osx-amd64.zip
#+end_src
Run ~rclone config~ for setting up the necessary configuration

** Mac: Install Iosevka font
#+begin_src sh :eval no
  brew tap homebrew/cask-fonts && brew install font-iosevka
#+end_src

** Mac: Install repomix for loading code into an llm
#+begin_src fish
  brew install repomix
#+end_src

** Mac: Install espanso for convenient text-expansion outside Emacs

#+begin_src fish
  brew tap espanso/espanso;
  brew install espanso;
#+end_src

** Mac: Install tools for working with data
#+begin_src fish
  brew install sqlite-utils datasette
#+end_src
** Mac: Install all the agents
*** Codex and Opencode
#+begin_src fish
  brew install codex anomalyco/tap/opencode
#+end_src
*** Pi Agent
#+begin_src fish
  bun install -g @mariozechner/pi-coding-agent
#+end_src
*** Claude Code
#+begin_src fish
  curl -fsSL https://claude.ai/install.sh | bash
#+end_src
